# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_shasum', models.CharField(default=b'', max_length=255, unique=True)),
                ('acd_shasum', models.CharField(default=b'', max_length=255)),
                ('path', models.CharField(default=b'', max_length=255)),
                ('is_dir', models.BooleanField(default=False)),
            ],
        ),
    ]
