# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='local_shasum',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
