# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_entry_last_check_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='prev_path',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
